name: storychat
description: Chats & Calling app

version: 2.0.11+12
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  extended_image: ^8.2.1
  flutter_image_compress: ^2.3.0
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  ffmpeg_kit_flutter: ^6.0.3
#  flutter_launcher_plus: 0.0.6
  font_awesome_flutter: ^10.7.0
  image_editor: ^1.5.1

  google_translate: 0.0.6
  logger: 1.4.0
  cloud_functions: ^5.0.1
  audioplayers: ^6.0.0
#  pin_input_text_field: 4.2.0
  audio_session: ^0.1.19
  flutter_cache_manager: ^3.3.1
  rxdart: ^0.27.7
  better_open_file: ^3.6.5
#  file_saver: 0.1.1
  gallery_saver: 2.3.2
  url_launcher: ^6.3.0
  circular_countdown_timer: ^0.2.3
  camera: ^0.11.0+1
  oktoast: ^3.4.0
  holding_gesture: ^1.2.0
  flutter_emoji: ^2.5.1
  pip_view: ^0.9.7
#  page_transition: 2.0.5
  wechat_assets_picker: ^9.0.4
  video_editor: 3.0.0
  mime: ^1.0.5
  video_compress: 3.1.2
  link_preview_generator: 1.2.0
#  any_link_preview: 3.0.1
  google_mobile_ads: ^5.1.0
  sms_autofill: ^2.4.0
  receive_sharing_intent: ^1.8.0
#  firebase_crashlytics: 3.0.3
  async: 2.11.0
  emoji_picker_flutter: ^2.2.0
  flutter_video_info: ^1.3.2
#  group_button: 3.3.1
#  flutter_colorpicker: 0.6.1
  devicelocale: ^0.7.1
#  http_auth: 1.0.2
  cloud_firestore: ^5.0.1
  flutter_cached_pdfview: ^0.4.2
  firebase_messaging: ^15.0.1
  firebase_storage: ^12.0.1
  device_info_plus: ^10.1.0
  file_picker: ^8.0.4
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_sound: 9.2.13
  percent_indicator: ^4.2.3
#  string_validator: 1.0.0
  ntp: 2.0.0
#  random_string: 2.3.1
#  flutter_native_timezone: 2.0.0
  intl: ^0.19.0
#  connectivity_plus: 3.0.3
  http: 1.1.0
  provider: ^6.1.2
  firebase_auth: ^5.1.0
#  html: 0.15.4
#  universal_platform: 1.0.0+1
  flutter_linkify: ^6.0.0
#  dotted_border: 2.0.0+1
#  diacritic: 0.1.3
#  image_cropper: 1.5.1
  contacts_service: 0.6.3
  share: 2.0.4
  scoped_model: ^2.0.0
  local_auth: ^2.2.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  localstorage: ^5.0.0
  # photo_view: 0.12.0
  # flutter_photo_view: 1.0.3
#  launch_review: 3.0.1
  overlay_support: ^2.1.0
  jiffy: ^6.3.1
  geolocator: ^12.0.0
  video_player: ^2.8.7
  video_thumbnail: 0.5.3
  chewie: ^1.8.1
  media_info: ^0.12.0+2
  firebase_core: ^3.1.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  agora_rtc_engine: ^6.3.2
  flutter_local_notifications: ^17.1.2
  flutter_secure_storage: ^9.2.2
  package_info_plus: ^8.0.0
  giphy_get: ^3.5.5
  wakelock_plus: ^1.2.5
#  cupertino_icons: 1.0.5
  collection: any
#  dropdown_plus: 0.0.9
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^5.0.15
  flutter_driver:
    sdk: flutter
  test: ^1.16.8

dependency_overrides:
  http: "0.13.4"
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/appicon/appicon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/appicon/
    - assets/images/
    - assets/sounds/
    - assets/flags/
    - lib/Services/localization/json_languages/
